-- MySQL Script generated by MySQL Workbench
-- Mon Apr  9 17:44:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenda` DEFAULT CHARACTER SET utf8 ;
USE `agenda` ;

-- -----------------------------------------------------
-- Table `agenda`.`utilizadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`utilizadores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `apelido` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`contactos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telemovel` INT(9) NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `utilizadores_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `utilizadores_id`),
  INDEX `fk_contactos_utilizadores_idx` (`utilizadores_id` ASC),
  CONSTRAINT `fk_contactos_utilizadores`
    FOREIGN KEY (`utilizadores_id`)
    REFERENCES `agenda`.`utilizadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
